{
 "title": "OPS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Host CPU % Utilization - Top 3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "max_cpu",
     "select": [
      [
       { "params": [ "max_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Host Memory Utilization - Top 3 (GB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "max_memory",
     "select": [
      [
       { "params": [ "max_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Host  Disk  % Usage - Top 3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "max_disk_usage",
     "select": [
      [
       { "params": [ "max_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Host  Disk IO % Utilization - Top 3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "max_disk_io",
     "select": [
      [
       { "params": [ "max_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Host Network % Utilization (Input)-  Top 3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "max_network_in",
     "select": [
      [
       { "params": [ "max_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Host  Network % Utilization (Output) -Top 3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "max_network_out",
     "select": [
      [
       { "params": [ "max_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests  served",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.backend.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bad Responses served",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.backend.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "code", "operator": "=", "value": "500" },
      { "condition": "OR", "key": "code", "operator": "=", "value": "502" },
      { "condition": "OR", "key": "code", "operator": "=", "value": "404" }
     ]
    }
   ]
  },
  {
   "title": "Average Response Time(Sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.backend.request.duration",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "P50" ], "type": "alias" }
      ],
      [
       { "params": [ "p90" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "P90" ], "type": "alias" }
      ],
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "P95" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "P99" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "backend" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.backend.connections.open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "code" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik.entrypoint.request.duration",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gitlab - Stuck imports",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "stuck_import_jobs" }
     ]
    }
   ]
  },
  {
   "title": "Gitlab - Avg Response time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 23 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rails_transactions",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gitlab - No of email triggered",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "receive_email" }
     ]
    }
   ]
  },
  {
   "title": "Gitlab - Builds",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "build_found" }
     ]
    }
   ]
  },
  {
   "title": "Commit per Project in Master and Branch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Master" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "push_commit" },
      { "condition": "AND", "key": "branch", "operator": "=", "value": "master" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Branch" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "push_commit" },
      { "condition": "AND", "key": "branch", "operator": "!=", "value": "master" }
     ]
    }
   ]
  },
  {
   "title": "Gitlab - Avg Commit Time (Sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sidekiq_transactions",
     "select": [
      [
       { "params": [ "find_commit_real_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg  Commit Time" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}